// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.contentblocking.category", "strict");
user_pref("browser.dom.window.dump.enabled", false);
user_pref("browser.migration.version", 166);
user_pref("browser.policies.applied", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.safebrowsing.provider.google4.dataSharingURL", "");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"]},\"seen\":[],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("captivedetect.canonicalURL", "");
user_pref("devtools.console.stdout.chrome", false);
user_pref("devtools.debugger.remote-enabled", false);
user_pref("distribution.iniFile.exists.appversion", "150.0.3-1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260512154104");
user_pref("extensions.lastAppVersion", "150.0.3-1");
user_pref("extensions.lastPlatformVersion", "150.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"c002c487-744b-4d63-9259-841e2231a68b\",\"formautofill@mozilla.org\":\"9514898d-8db4-4a38-8938-4ecd98753770\",\"ipp-activator@mozilla.com\":\"e6b67253-2432-442b-b43d-0df5cb7a76a5\",\"pictureinpicture@mozilla.org\":\"86a1fed5-c196-47cf-8e43-2e898dc20afb\",\"addons-search-detection@mozilla.com\":\"c76c2346-6db0-4137-8af3-f7127abaa1b1\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"cd94bcc4-24c9-496f-8a6a-37ac70143710\",\"default-theme@mozilla.org\":\"cc5b78f2-6972-43cd-a88d-52d2a02702d7\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.early-hints.preconnect.max_connections", 0);
user_pref("network.http.http3.enable_0rtt", false);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.prefetch-next", false);
user_pref("nimbus.profileId", "42ee32d3-8467-42c9-a4f3-2f28d31f8afd");
user_pref("pdfjs.enabledCache.state", true);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.history.custom", true);
user_pref("security.tls.enable_0rtt_data", false);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.winRegisterApplicationRestart", false);
