#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set Workspace Names
bspc monitor -d 1 2 3 4

# Set Padding For PolyBar
bspc config top_padding         28
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Restore Wallpaper
bash ~/.fehbg
